In [1]:
import sys
print(sys.version)

3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609]


In [2]:
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')

In [3]:
import cv2 as cv
import numpy as np
print(cv.__version__)

4.1.0


In [4]:
cap = cv.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()

    # Our operations on the frame come here
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)

    # Display the resulting frame
    cv.imshow('frame',gray)
    if cv.waitKey(1) & 0xFF == ord('q'):
        break

# When everything done, release the capture
cap.release()
cv.destroyAllWindows()

error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'


In [4]:
import sys
sys.path.append('../../rai/rai/ry')
import libry as ry
import numpy as np

In [5]:
cam = ry.Camera()

In [16]:
while(True):
    # Capture frame-by-frame
    frame = cam.getRgb()
    depth = cam.getDepth()

    # Display the resulting frame
    cv.imshow('frame',frame)
    cv.imshow('depth',depth)
    if cv.waitKey(1) & 0xFF == ord('q'):
        break

In [6]:
C = ry.Config()
D = C.view()
C.clear()
C.addFile('../../rai-robotModels/baxter/baxter.g')

In [5]:
pcl = C.addFrame("pcl")

In [6]:
pcl.setBox([1,1,1,.2])

In [11]:
pcl = C.addObject(name='pcl2', parent='world', shape=ry.ST.mesh, mesh=P)

TypeError: addObject(): incompatible function arguments. The following argument types are supported:
    1. (self: libry.Config, name: str, parent: str = '', shape: rai::ShapeType, size: List[float] = [], color: List[float] = [], pos: List[float] = [], quat: List[float] = [], radius: float = -1.0) -> ry::RyFrame

Invoked with: <libry.Config object at 0x7fc0304346c0>; kwargs: parent='world', shape=ST.mesh, mesh=array([[[-1.32200003,  0.99150002, -1.32200003],
        [-1.32384992,  0.99599999, -1.32799995],
        [-1.31373751,  0.99150002, -1.32200003],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[-1.32200003,  0.98736876, -1.32200003],
        [-1.32384992,  0.99185002, -1.32799995],
        [-1.31373751,  0.98736876, -1.32200003],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[-1.32200003,  0.98323756, -1.32200003],
        [-1.31786883,  0.98323756, -1.32200003],
        [-1.31373751,  0.98323756, -1.32200003],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       ...,

       [[-1.49600005, -1.10797501, -1.49600005],
        [-1.49132514, -1.10797501, -1.49600005],
        [-1.47969365, -1.10279059, -1.48899996],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[-1.49600005, -1.11265004, -1.49600005],
        [-1.49132514, -1.11265004, -1.49600005],
        [-1.47969365, -1.10744369, -1.48899996],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]],

       [[-1.49600005, -1.11732507, -1.49600005],
        [-1.49132514, -1.11732507, -1.49600005],
        [-1.47969365, -1.11209691, -1.48899996],
        ...,
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ]]]), name='pcl2'

In [8]:
P = cam.getPoints([320., 320., 320., 240.])

In [9]:
pcl2.setPointCloud(P)

In [10]:
pcl2.setBox([.2,.2,.2,.05])

In [14]:
P.shape

(480, 640, 3)

In [15]:
print(P)

[[[-1.32200003  0.99150002 -1.32200003]
  [-1.32384992  0.99599999 -1.32799995]
  [-1.31373751  0.99150002 -1.32200003]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[-1.32200003  0.98736876 -1.32200003]
  [-1.32384992  0.99185002 -1.32799995]
  [-1.31373751  0.98736876 -1.32200003]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [[-1.32200003  0.98323756 -1.32200003]
  [-1.31786883  0.98323756 -1.32200003]
  [-1.31373751  0.98323756 -1.32200003]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 ...

 [[-1.49600005 -1.10797501 -1.49600005]
  [-1.49132514 -1.10797501 -1.49600005]
  [-1.48665011 -1.10797501 -1.49600005]
  ...
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]
  [ 0.          0.          0.        ]]

 [